<?php

/**
 * Implementation of hook_install().
 */
function ca_applications_install() {
  variable_set('ca_applications_application_list_template', 'ca_applications_application_list_template_one');
  variable_set('ca_applications_application_node_template', 'ca_applications_application_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_applications_uninstall() {
  variable_del('ca_applications_application_list_template');
  variable_del('ca_applications_application_node_template');
}
