<?php

include_once('ca_applications.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_applications_perm() {
  return array('ca_applications change templates');
}

/**
 * Implementation of hook_menu().
 */
function ca_applications_menu() {
  $items['admin/settings/ca_applications'] = array(
    'title' => 'Context Admin: Applications',
    'description' => 'Change the look and feel of the ca_applications feature.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_applications_admin_settings_form'),
    'access arguments' => array('ca_applications change templates'),
    'file' => 'ca_applications.admin.inc',
    'file path' => drupal_get_path('module', 'ca_applications') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_applications_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_applications_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_applications_application_list' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_applications') . "/css/ca_applications.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_applications_views_pre_render(&$view) {
  if ($view->name == 'ca_applications') {
    drupal_add_css(drupal_get_path('module', 'ca_applications') . "/css/ca_applications.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_token_list().
 */
function ca_applications_token_list($type = 'all') {
  $tokens = array();

  if ($type == 'node' || $type == 'all') {
    // Node tokens here.
    $tokens['node']['ca-applications-related-app-reference-path'] = t("WARNING: This token expects a particular node reference field. This should never be used outside of the ca_applications feature.");
  }

  return $tokens;
}

/**
 * Implementation of hook_token_values().
 */
function ca_applications_token_values($type, $object = NULL) {
  $values = array();
  switch ($type) {
    case 'node':
      // Node tokens here.
      $parent_app_id = $object->field_ca_products_related_app[0]['nid'];
      $parent_app_node = node_load($parent_app_id);
      $parent_app_node_path = $parent_app_node->path;
      if ($parent_app_id != '') {
        $values['ca-applications-related-app-reference-path'] = $parent_app_node_path;
      }
      else {
        $values['ca-applications-related-app-reference-path'] = 'applications';
      }
      break;
  }
  return $values;
}
